### ISSUE TITLE
Installation script fails on importing modules

### ISSUE THREAD

**Issue by Enotian** [Patrowl/PatrowlHears#114]
Hello,

I'm having an issue for the installation of the application. I use the install script, and I get a lot of errors while it calls the manage.py file. In facts, it seems that it can't finds and import the modules installed in the previous step using the requirements.txt list . Then I tryed to install the modules manually both on the machine itself and in the virtual env. Unfortunatly, it does not fix the installation yet.

Here's a log of one of the imports errors :

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 12, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
[+] Create default admin private organization if needed
Traceback (most recent call last):
  File "manage.py", line 10, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

I also get an error after in installation of mongoengine :

ERROR: Command errored out with exit status 1:
     command: /home/user/PatrowlHears/backend_app/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bn8qjhq3/mongoengine_e9130316855643b289f33a549bc88a87/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bn8qjhq3/mongoengine_e9130316855643b289f33a549bc88a87/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-o1osxapb
         cwd: /tmp/pip-install-bn8qjhq3/mongoengine_e9130316855643b289f33a549bc88a87/
    Complete output (1 lines):
    error in mongoengine setup command: use_2to3 is invalid.

When the installation is finished, and when I try to connect the application interface, I get a "502 - Bad Gateway message". This installation process worked really fine 3 or 4 month ago. I feel like I'm missing something. 
I am using a VM on Ubuntu server 20.04.3 .

Thank you in advance for your help.

Have a nice day

**Comment by NoeJuzaAltis** [comment]
Heya,
Exact same issue on docker-compose version
## System informations
TYPE: VM
OS: Ubuntu 18.04.5 LTS x86_64
Docker version: 20.10.9
docker-compose version: 1.29.2
