### ISSUE TITLE
[Support]  - Installation Failed cause bad password

### ISSUE THREAD

**Issue by Makeuu** [Patrowl/PatrowlHears#127]
Hi, i am trying to install PatrowHers. I followed the second way to install and at the end i have the log on interface but the login and the password "admin" and "Bonjour1!" didn't worked. Have you already seen this ? maybe i failed one step ?
Maybe the script failed to create the user ?

Thanks you

**Comment by alexmartz001** [comment]
hello excellent work, just like I have installed the second case and the third but I have the same error.

**Comment by KossiJunior** [comment]
Hi,

Same problem here; seem like it's related to django module interaction with the postgresql database. These logs appears in backend_app/var/log/django-debug.log when i try to log on web interface using default credentials.

```
2022-02-18 10:18:01,425 django.request ERROR    Internal Server Error: /auth-jwt/obtain_jwt_token/
Traceback (most recent call last):
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/rest_framework_simplejwt/views.py", line 27, in post
    serializer.is_valid(raise_exception=True)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 422, in run_validation
    value = self.validate(value)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/rest_framework_simplejwt/serializers.py", line 71, in validate
    data = super().validate(attrs)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/rest_framework_simplejwt/serializers.py", line 43, in validate
    self.user = authenticate(**authenticate_kwargs)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/home/patrowl/PatrowlHears/backend_app/users/backends.py", line 81, in authenticate
    for user in users:
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor = self.connection.cursor()
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/patrowl/PatrowlHears/backend_app/env/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: fe_sendauth: no password supplied
```
